"""Middleware that fills in a real filename on ``read_file`` file attachments.

**Why this exists**

``deepagents``' built-in ``read_file`` tool returns non-text files (PDF,
PPT/PPTX, images, audio, video) as a standard multimodal content block::

    {"type": "file", "base64": "...", "mime_type": "application/pdf"}

Note the absence of a ``filename``.  When ``langchain_core`` serialises this
block for the OpenAI Chat Completions wire format (used by the ``openai``,
``omlx`` and ``exo`` providers), ``convert_to_openai_data_block`` can't find a
``filename`` anywhere on the block and falls back to a placeholder::

    {"type": "file", "file": {"file_data": "data:application/pdf;base64,...",
                               "filename": "LC_AUTOGENERATED"}}

Extension-less placeholder filenames like this then get rejected by servers
that sniff the attachment type from the filename's extension — e.g. the local
oMLX server replies with ``400 Unsupported attachment type. Supported formats
are PDF, DOCX, PPTX, TXT, and MD.`` even though the file *is* a valid PDF.

**What it does**

Before each model call it scans the message history for ``ToolMessage``
"file" content blocks that lack a ``filename``, and — using the source path
``read_file`` stashes in ``additional_kwargs["read_file_path"]`` — fills in a
real filename (with the correct extension) so downstream serialisation never
falls back to the extension-less placeholder.

The transform is applied to a throwaway copy of the request (via
``request.override``) and is recomputed from canonical state on every call,
so it is idempotent and never mutates the persisted conversation.
"""

from __future__ import annotations

import mimetypes
from collections.abc import Awaitable, Callable
from pathlib import Path
from typing import Any

from langchain.agents.middleware import AgentMiddleware
from langchain.agents.middleware.types import ModelRequest, ModelResponse
from langchain_core.messages import ToolMessage


def maybe_for_model(model: Any) -> "FileAttachmentFilenameMiddleware | None":
    """Return the middleware when *model* speaks the OpenAI Chat Completions API.

    Gating on ``BaseChatOpenAI`` (the common base of ``ChatOpenAI`` and
    ``AzureChatOpenAI``, which is what the ``openai``/``omlx``/``exo``
    providers instantiate) makes this a no-op for Anthropic, Bedrock and MLX
    models — only the OpenAI wire format needs a ``filename`` on file blocks.
    """
    try:
        from langchain_openai.chat_models.base import BaseChatOpenAI
    except ImportError:
        return None
    if not isinstance(model, BaseChatOpenAI):
        return None
    return FileAttachmentFilenameMiddleware()


def _is_filenameless_file_block(block: Any) -> bool:
    """Return ``True`` for a "file" content block that has no filename."""
    if not isinstance(block, dict) or block.get("type") != "file":
        return False
    if block.get("filename"):
        return False
    extras = block.get("extras")
    if isinstance(extras, dict) and extras.get("filename"):
        return False
    return True


def _guess_filename(mime_type: str | None) -> str:
    """Best-effort generic filename for a mime type when no path is known."""
    ext = mimetypes.guess_extension(mime_type or "") or ""
    return f"upload{ext}"


class FileAttachmentFilenameMiddleware(AgentMiddleware):
    """Fill in real filenames on ``read_file`` attachments for OpenAI-compatible providers.

    Insert this for providers whose transport is the OpenAI Chat Completions
    API (``openai``, ``omlx``, ``exo``).  It is a no-op when no ``ToolMessage``
    in the history carries a filename-less "file" content block, so it is
    safe to include unconditionally for those providers.
    """

    def wrap_model_call(
        self,
        request: ModelRequest,
        handler: Callable[[ModelRequest], ModelResponse],
    ) -> ModelResponse:
        return handler(self._fix_request(request))

    async def awrap_model_call(
        self,
        request: ModelRequest,
        handler: Callable[[ModelRequest], Awaitable[ModelResponse]],
    ) -> ModelResponse:
        return await handler(self._fix_request(request))

    # ── Private helpers ─────────────────────────────────────────────────────

    def _fix_request(self, request: ModelRequest) -> ModelRequest:
        fixed = self._fix_filenames(list(request.messages))
        if fixed is None:
            return request
        return request.override(messages=fixed)

    def _fix_filenames(self, messages: list[Any]) -> list[Any] | None:
        """Return a new message list with filenames added to file blocks
        that are missing one, or ``None`` when there is nothing to fix.
        """
        changed = False
        out: list[Any] = []

        for msg in messages:
            if not (isinstance(msg, ToolMessage) and isinstance(msg.content, list)):
                out.append(msg)
                continue

            if not any(_is_filenameless_file_block(b) for b in msg.content):
                out.append(msg)
                continue

            changed = True
            source_path = msg.additional_kwargs.get("read_file_path")
            filename = Path(source_path).name if source_path else None

            new_content = []
            for block in msg.content:
                if _is_filenameless_file_block(block):
                    block = dict(block)
                    block["filename"] = filename or _guess_filename(block.get("mime_type"))
                new_content.append(block)
            out.append(msg.model_copy(update={"content": new_content}))

        return out if changed else None
