"""Tests for ``FileAttachmentFilenameMiddleware``.

``deepagents``' ``read_file`` tool returns non-text files (PDF, PPTX, etc.)
as a "file" content block with no ``filename``. When that block is
serialised for the OpenAI Chat Completions wire format, ``langchain_core``
falls back to a placeholder filename with no extension
(``"LC_AUTOGENERATED"``), which some OpenAI-compatible servers (e.g. the
local oMLX server) reject outright as an "Unsupported attachment type" even
though the file is a valid PDF. The middleware fills in a real filename
(derived from the path ``read_file`` read) before that conversion happens.
"""

from __future__ import annotations

from langchain_core.messages import AIMessage, HumanMessage, SystemMessage, ToolMessage

from middleware.file_attachment_filename import FileAttachmentFilenameMiddleware


def _pdf_tool_message(call_id: str, path: str) -> ToolMessage:
    return ToolMessage(
        tool_call_id=call_id,
        name="read_file",
        content=[{"type": "file", "base64": "AAAA", "mime_type": "application/pdf"}],
        additional_kwargs={"read_file_path": path, "read_file_media_type": "application/pdf"},
    )


def test_fills_in_filename_from_read_file_path():
    mw = FileAttachmentFilenameMiddleware()
    tm = _pdf_tool_message("c1", "/uploads/Eugene Tan CV - Full.pdf")
    messages = [
        SystemMessage(content="sys"),
        HumanMessage(content="read my cv"),
        AIMessage(
            content="",
            tool_calls=[{"name": "read_file", "args": {}, "id": "c1", "type": "tool_call"}],
        ),
        tm,
    ]

    out = mw._fix_filenames(messages)
    assert out is not None

    fixed_tool_msgs = [m for m in out if isinstance(m, ToolMessage)]
    assert len(fixed_tool_msgs) == 1
    block = fixed_tool_msgs[0].content[0]
    assert block["type"] == "file"
    assert block["filename"] == "Eugene Tan CV - Full.pdf"


def test_falls_back_to_mime_type_when_no_read_file_path():
    mw = FileAttachmentFilenameMiddleware()
    tm = ToolMessage(
        tool_call_id="c1",
        content=[{"type": "file", "base64": "AAAA", "mime_type": "application/pdf"}],
    )
    out = mw._fix_filenames([tm])
    assert out is not None
    assert out[0].content[0]["filename"] == "upload.pdf"


def test_noop_when_filename_already_present():
    mw = FileAttachmentFilenameMiddleware()
    tm = ToolMessage(
        tool_call_id="c1",
        content=[{"type": "file", "base64": "AAAA", "mime_type": "application/pdf", "filename": "report.pdf"}],
        additional_kwargs={"read_file_path": "/uploads/report.pdf"},
    )
    assert mw._fix_filenames([tm]) is None


def test_noop_when_no_file_blocks():
    mw = FileAttachmentFilenameMiddleware()
    messages = [
        SystemMessage(content="sys"),
        HumanMessage(content="hello"),
        AIMessage(content="hi"),
        ToolMessage(tool_call_id="c1", content="plain text result"),
    ]
    assert mw._fix_filenames(messages) is None


def test_does_not_mutate_input_messages():
    mw = FileAttachmentFilenameMiddleware()
    tm = _pdf_tool_message("c1", "/uploads/report.pdf")
    messages = [HumanMessage(content="q"), AIMessage(content=""), tm]

    mw._fix_filenames(messages)

    # The original tool message is untouched (transform is on a copy).
    assert "filename" not in tm.content[0]
