"""Source-bundled built-in MCP servers.

Each subfolder here is the canonical source for one built-in MCP that
ships with the backend.  The shape mirrors what
:mod:`backend.mcp_builder` produces for agent-authored servers
(``server.py`` + ``requirements.txt``), but the source lives in the
repo so:

* fresh installs get the server out of the box (no agent step required);
* updates ride the same release as the rest of the backend;
* the audit trail is git, not a file the user might have edited.

On every backend startup :func:`sync_builtin_mcp_files` copies these
source files into ``<app_data>/mcp_server/<id>/`` (overwriting any
in-place changes), and :func:`ensure_builtin_mcp_venvs` provisions a
``.venv`` next to them via ``uv``.  The :class:`MCPServerConfig`
generated by :mod:`backend.config` points at the venv interpreter, so
spawning the subprocess works exactly like an agent-built MCP.
"""

from __future__ import annotations

from .registry import (
    BUILTIN_MCPS,
    BuiltinMCP,
    builtin_mcp_config,
    ensure_builtin_mcp_venvs,
    sync_builtin_mcp_files,
)

__all__ = [
    "BUILTIN_MCPS",
    "BuiltinMCP",
    "builtin_mcp_config",
    "ensure_builtin_mcp_venvs",
    "sync_builtin_mcp_files",
]
